### ISSUE TITLE
FormBuilderChipsInput, Exception: A FocusNode was used after being disposed

### ISSUE THREAD

**Issue by Draxent** [danvick/flutter_form_builder#313]
I am using the code provided in the [example page](https://github.com/danvick/flutter_form_builder/blob/master/example/lib/main.dart).
When typing a new person in the **FormBuilderChipsInput**, then releasing the keyboard and then trying to write something else, I get the following error:

```
E/flutter (15302): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: A FocusNode was used after being disposed.
E/flutter (15302): Once you have called dispose() on a FocusNode, it can no longer be used.
E/flutter (15302): #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> 
package:flutter/…/foundation/change_notifier.dart:106
E/flutter (15302): #1      ChangeNotifier._debugAssertNotDisposed 
package:flutter/…/foundation/change_notifier.dart:112
E/flutter (15302): #2      ChangeNotifier.notifyListeners 
package:flutter/…/foundation/change_notifier.dart:201
E/flutter (15302): #3      FocusNode._notify 
package:flutter/…/widgets/focus_manager.dart:970
E/flutter (15302): #4      FocusManager._applyFocusChange
```
As you can see from the image below, the suggestion is not showed when writing "pa".

![image](https://user-images.githubusercontent.com/4294247/84086017-2914f400-a9e7-11ea-81a0-913c6d22a9f8.png)

**Comment by RedTech64** [comment]
I have this widget on a drawer, and I get this same error.

**Comment by danvick** [comment]
Thanks for bringing this to my attention @Draxent & @RedTech64.
I'm resolving the issue (along with others) over there in chips_input package repository and will be pulling in the updated version with a fix soon.

**Comment by stact** [comment]
Same issue on version_4

**Comment by Gizmo1337** [comment]
Same issue with FormBuilderRadioGroup

`E/flutter ( 4293): Once you have called dispose() on a FocusNode, it can no longer be used.
E/flutter ( 4293): #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:117:9)
E/flutter ( 4293): #1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:123:6)
E/flutter ( 4293): #2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:217:12)
E/flutter ( 4293): #3      FocusNode._notify (package:flutter/src/widgets/focus_manager.dart:1027:5)
E/flutter ( 4293): #4      FocusManager._applyFocusChange (package:flutter/src/widgets/focus_manager.dart:1723:12)
E/flutter ( 4293): #5      _rootRun (dart:async/zone.dart:1182:47)
E/flutter ( 4293): #6      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 4293): #7      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter ( 4293): #8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter ( 4293): #9      _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 4293): #10     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 4293): #11     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter ( 4293): #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter ( 4293): #13     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 4293): #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter ( 4293): `

**Comment by wadihhannouch** [comment]
Hello all 

Any news regarding this error?

**Comment by dharmeshSearce** [comment]
Hello All,
I got an error while i  select **FormBuilderChipsInputA** and after i change the **FormBuilderDateTimePicker**  got this error **FocusNode was used after being disposed.** please help me.

**Comment by DSolanki91** [comment]
@danvick please help us for this error.

**Comment by rajd90** [comment]
I'm getting the same error using FormBuilderChipsInput, using flutter_form_builder: ^3.14.1 (I couldn't use >= v4 due to some conflicts and build errors).

Is there any update on a fix for this?

```
E/flutter ( 9659): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: A FocusNode was used after being disposed.
E/flutter ( 9659): Once you have called dispose() on a FocusNode, it can no longer be used.
E/flutter ( 9659): #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure>
package:flutter/…/foundation/change_notifier.dart:117
E/flutter ( 9659): #1      ChangeNotifier._debugAssertNotDisposed
package:flutter/…/foundation/change_notifier.dart:123
E/flutter ( 9659): #2      ChangeNotifier.notifyListeners
package:flutter/…/foundation/change_notifier.dart:217
E/flutter ( 9659): #3      FocusNode._notify
package:flutter/…/widgets/focus_manager.dart:1027
E/flutter ( 9659): #4      FocusManager._applyFocusChange
package:flutter/…/widgets/focus_manager.dart:1723
E/flutter ( 9659): #5      _rootRun (dart:async/zone.dart:1182:47)
E/flutter ( 9659): #6      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 9659): #7      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter ( 9659): #8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter ( 9659): #9      _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 9659): #10     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 9659): #11     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter ( 9659): #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter ( 9659): #13     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 9659): #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

```

**Comment by Dinosane2** [comment]
Same here!

**Comment by bbence84** [comment]
Same issue. Not sure, which widget is causing it, though. But my date and time picker definetly shows this error after a while. :( @danvick : is it possible to address this? Thanks!

**Comment by Purus** [comment]
The below code causes this issuef or me.

```
                FormBuilderDateTimePicker(
                  name: 'date',
                  // onChanged: _onChanged,
                  inputType: InputType.date,
                  decoration: InputDecoration(
                    labelText: 'Date of Birth',
                  ),
                ),
```

**Comment by bbence84** [comment]
Well, I did the following: I edited form_builder_date_time_picker.dart and uncommented the contents of the dispose method.
That seem to have adressed the issue.
But I am a flutter newbie, so I have no idea about the consequences, maybe this will eventually lead to a memory leak...

**Comment by icfilho** [comment]
I have same problem with FormBuilderChoiceChip and solved using property focusNode.

Ex.:

`FocusNode focusNode;

  @override
  void initState() {
    super.initState();

    focusNode = FocusNode();
  }
@override
  void dispose() {
    focusNode.dispose();
    super.dispose();
  }

FormBuilderChoiceChip(
        focusNode: focusNode,
....
`

**Comment by slavap** [comment]
I'm getting this error all the time, and the only solution was commenting out _focusNode.dispose() in FormBuilderFieldState
```dart
  @override
  void dispose() {
    _focusNode.removeListener(_touchedHandler);
    // Dispose focus node when created by initState
    if (null == widget.focusNode) {
      //_focusNode.dispose(); <-- Causes "A FocusNode was used after being disposed"
    }
    _formBuilderState?.unregisterField(widget.name, this);
    super.dispose();
  }
```
It looks not very correct, but I just cannot figure it out where the real problem is.

**Comment by Purus** [comment]
I am getting your very often too. Any help would be appreciated.

**Comment by jigarfumakiya** [comment]
I am getting this issue in `FormBuilderDropdown` as well,
Any update ?

**Comment by slavap** [comment]
@jigarfumakiya use fix from linked https://github.com/danvick/flutter_form_builder/issues/703

**Comment by jigarfumakiya** [comment]
Thanks That worked @slavap

**Comment by dknightone** [comment]
Ran into the same problem.  After testing different combinations of interactions, I discovered that if I restart the application, and interact with the FormBuilderDateTimePicker control __first__, it works.  However, if I interact with a FormBuilderSegmentedControl, and then try to click on FormBuilderDateTimePicker control, the date time picker throws the focus exception.

The solution that worked for me, without making any modifications to the original flutter_form_builder code was to update my calls to FormBuilderSegmentedControl, and set the focusNode property.  See below.

FormBuilderSegmentedControl(
  ...
  focusNode: FocusNode(),  // added attribute
  ...
)

There is an issue w/ how FormBuilderField<T> is disposing the focusNode.  It becomes an issue if application is hot reloaded.  You may have to do a hot restart instead.

**Comment by Goxiaoy** [comment]
Make sure you use the same formKey every rebuild. 
Do not  create this in Statelesswidget
```
  final formKey = GlobalKey<FormBuilderState>();
```
Or put the codes in build method

**Comment by slavap** [comment]
@Goxiaoy formKey does not help

**Comment by saltatory** [comment]
Just want to chime in ... I had some of the same issues as described above.

When I use the `FormBuilderSearchableDropdown` I end up with one or more of the following:

* Multiple `TextField`s will get focus at the same time
* I will get an error about a FocusNode being used after being `dispose()`d
* The `TextInputAction.next` will not correctly navigate to the next field.

In my local copy of `flutter_form_builder` I made the following change to `form_builder_searchable_dropdown.dart` starting on Line 173:

```dart
                onChanged: (val) {
                  // Per https://github.com/danvick/flutter_form_builder/issues/703
                  // state.requestFocus();
                  state.didChange(val);
                },

```

This change resulted in all my dropdowns and `FormBuilderTextField`s working properly. No errors in the log. No funny behavior in the app.

I'm commenting here to help out. I haven't had the time (yet) to figure out whether this is a general solution and submit a PR.

**Comment by yarmel** [comment]
FormBuilderCheckbox & Chips  -- the same issue.  Once you have called dispose() on a FocusNode, it can no longer be used.

**Comment by iDevOrz** [comment]
When I use the `FormBuilderSwitch`, I had  the same issues as described above.
@saltatory 's comments is Helpful for me.
But it make a new issues ,When I am Click the Switch  Button ,The TextFields can't resign FirstResponder.
I fix it by override `requestFocus func`:

```dart
  @override
  void requestFocus() {
    FocusScope.of(context).unfocus();
  }
```

reference： https://stackoverflow.com/questions/44991968/how-can-i-dismiss-the-on-screen-keyboard

I will submit a PR later.

**Comment by ojm-it** [comment]
@iDevOrz @saltatory Your fixes are just workarounds and not actual fixes, because the normal behaviour would be to actually request the focus. So this should stay unchanged : 

```
  void requestFocus() {
    FocusScope.of(context).requestFocus(effectiveFocusNode);
  }
```

I found out that the real reason this bug happens is that for some FormBuilder fields, the `effectiveFocusNode` isn't assigned to the actual widget. 

Here is how I fixed it : 

### For FormBuilderChoiceChips, FormBuilderDropdown, FormBuilderFilterChips, FormBuilderSlider :
The widget used under the hood for each one of these FormBuilder fields have a `focusNode` parameter that I set to `state.effectiveFocusNode`.

For example, for FormBuilderChoiceChips :
```
ChoiceChip(
        focusNode: state.effectiveFocusNode, //Added this line
        label: option,
        selected: field.value == option.value,
        onSelected: state.enabled
            ? (selected) {
                final choice = selected ? option.value : null;
                state.requestFocus();
                state.didChange(choice);
              }
            : null,
            .......
```

### For FormBuilderCheckbox, FormBuilderCheckboxGroup, FormBuilderRadioGroup, FormBuilderRangeSlider, FormBuilderSegmentedControl, FormBuilderSwitch :
The widget used under the hood for each one of these FormBuilder fields don't have a `focusNode` parameter, so I wrapped them with a `Focus` widget which focusNode I set to `state.effectiveFocusNode`.

For example, for FormBuilderSwitch :
```
return Focus(
      canRequestFocus: enabled,
      focusNode: state.effectiveFocusNode, //This is the important part
      autofocus: autofocus,
      child: InputDecorator(
          decoration: state.decoration(),
          child: SwitchListTile( .......
```

I will try to submit a PR this week if I have time

**Comment by saltatory** [comment]
Great. Thanks for the excellent followup. I definitely learned something.

**Comment by slavap** [comment]
@ojm-it  By the way, Focus() workaround works, but adds undesirable effect with excessive Tab stop.
For example: radio group with Item1 and Item2, tab stops will be: Item1, Item2, “limbo”, next widget.

**Comment by wottpal** [comment]
@ojm-it looks great! did you had time filing that PR? I stumbled across the same issue lately.

**Comment by ojm-it** [comment]
@wottpal There is still the excessive tab stop @slavap talked about, and I currently don't have time to look up a solution for it. 

Maybe you can have a look at it? And then submit a PR with all these changes combined

**Comment by alpertungir** [comment]
> @iDevOrz @saltatory Your fixes are just workarounds and not actual fixes, because the normal behaviour would be to actually request the focus. So this should stay unchanged :
> 
> ```
>   void requestFocus() {
>     FocusScope.of(context).requestFocus(effectiveFocusNode);
>   }
> ```
> 
> I found out that the real reason this bug happens is that for some FormBuilder fields, the `effectiveFocusNode` isn't assigned to the actual widget.
> 
> Here is how I fixed it :
> 
> ### For FormBuilderChoiceChips, FormBuilderDropdown, FormBuilderFilterChips, FormBuilderSlider :
> The widget used under the hood for each one of these FormBuilder fields have a `focusNode` parameter that I set to `state.effectiveFocusNode`.
> 
> For example, for FormBuilderChoiceChips :
> 
> ```
> ChoiceChip(
>         focusNode: state.effectiveFocusNode, //Added this line
>         label: option,
>         selected: field.value == option.value,
>         onSelected: state.enabled
>             ? (selected) {
>                 final choice = selected ? option.value : null;
>                 state.requestFocus();
>                 state.didChange(choice);
>               }
>             : null,
>             .......
> ```
> 
> ### For FormBuilderCheckbox, FormBuilderCheckboxGroup, FormBuilderRadioGroup, FormBuilderRangeSlider, FormBuilderSegmentedControl, FormBuilderSwitch :
> The widget used under the hood for each one of these FormBuilder fields don't have a `focusNode` parameter, so I wrapped them with a `Focus` widget which focusNode I set to `state.effectiveFocusNode`.
> 
> For example, for FormBuilderSwitch :
> 
> ```
> return Focus(
>       canRequestFocus: enabled,
>       focusNode: state.effectiveFocusNode, //This is the important part
>       autofocus: autofocus,
>       child: InputDecorator(
>           decoration: state.decoration(),
>           child: SwitchListTile( .......
> ```
> 
> I will try to submit a PR this week if I have time

many thanks. it's solved by wrapping with Focus.

![image](https://user-images.githubusercontent.com/4275327/122078588-5fa8fa00-ce05-11eb-8911-21e4b0ac340f.png)

**Comment by alihesari** [comment]
@ojm-it @alpertungir But this way does not work for me! I got this error
```
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: A FocusNode was used after being disposed.
Once you have called dispose() on a FocusNode, it can no longer be used.
```

**Comment by seunghwanly** [comment]
`FormBuilderChoiceChip` was also occurring issue in my code and I solved this issue by using `effectiveFocusNode`.

Here is my sample code.
``` dart
final _formKey = GlobalKey<FormBuilderState>();

FormBuilderTextField(
  /// focusNode issue : used after dispose
  focusNode: _formKey.currentState?.fields['extraNotes']!.effectiveFocusNode, // added thisline
  name: 'extraNotes',
  maxLines: 3,
  keyboardType: TextInputType.multiline,
  ...
  // validator: validateRequired,
),

FormBuilderChoiceChip(
  /// focusNode issue : used after dispose
   focusNode: _formKey.currentState?.fields['repetition']!.effectiveFocusNode, // added thisline
   name: 'repetition',
   ...
   /// make validation for required
   validator: validateRequired,
),
```

and all FormBuilder Widgets are wrapped up with `FormBuilder` as well.

from adding `focusNode` with `: _formKey.currentState?.fields['{nameField}']!.effectiveFocusNode` it worked for me 👍

**Comment by alpertungir** [comment]
> @ojm-it @alpertungir But this way does not work for me! I got this error
> 
> ```
> [VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: A FocusNode was used after being disposed.
> Once you have called dispose() on a FocusNode, it can no longer be used.
> ```
Define global variable for focusNode and  initialize it on ctor

class _AppTypeEditFormState extends State<AppTypeEditForm> {
  AppType _appType;
  final _formKey = GlobalKey<FormBuilderState>();
  AutovalidateMode _autovalidateMode = AutovalidateMode.disabled;
  FocusNode _focusNode;

  @override
  void initState() {
    super.initState();
    _appType = AppType();
    _focusNode = FocusNode();
  }

**Comment by szymonmazanik** [comment]
Any update on this, please? @danvick 
I'm on the `7.0.0.alpha2` and still get the 
```
Unhandled Exception: A FocusNode was used after being disposed.
Once you have called dispose() on a FocusNode, it can no longer be used.
```
even on simple `FormBuilderTextField`. I get this after changing the state back and forth with flutter_bloc state manager.
I tried declaring `FocusNode` above the `FormBuilder`, tried global `GlobalKey` and local one, created in Statefull widget. Nothing seems to work for me.

If the issue is unsolvable I will have to remove this great package from my project  😕

**Comment by mrniamster** [comment]
Still getting this issue, not yet resolved...

`E/flutter ( 4320): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: A FocusNode was used after being disposed.
E/flutter ( 4320): Once you have called dispose() on a FocusNode, it can no longer be used.
E/flutter ( 4320): #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:114:9)
E/flutter ( 4320): #1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:120:6)
E/flutter ( 4320): #2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:288:12)
E/flutter ( 4320): #3      FocusNode._notify (package:flutter/src/widgets/focus_manager.dart:1145:5)
E/flutter ( 4320): #4      FocusManager._applyFocusChange (package:flutter/src/widgets/focus_manager.dart:1882:12)
E/flutter ( 4320): #5      _rootRun (dart:async/zone.dart:1420:47)
E/flutter ( 4320): #6      _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter ( 4320): #7      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter ( 4320): #8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter ( 4320): #9      _rootRun (dart:async/zone.dart:1428:13)
E/flutter ( 4320): #10     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter ( 4320): #11     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter ( 4320): #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter ( 4320): #13     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter ( 4320): #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter ( 4320):`

**Comment by bdthombre** [comment]
Had same problem with FormBuilderDropDown().

Use FormBuilderDropDown(
autofocus: false,
)

//Solved for me
return FormBuilderDropdown(
                  key: UniqueKey(),
                  autofocus: false,
                  decoration: buildInputDecoration("Sub Diagnosis"),
                  name: 'subDiagnosis',............}

**Comment by mapokapo** [comment]
Still having this problem with custom `FormBuilderField` widgets. The error occurs every time that the current route/page is changed i.e. a new page is pushed onto the stack or a modal dialog is shown (thus unmounting the widget).

Important to note is if the custom widget is not interacted with, then the error does not occur, but this could be due to an error in my own code. Also adding your own `FocusNode` to the custom widget and then calling `FocusNode.dispose()` in the widget dispose callback does not fix the issue.

Apart from the widget layout code, here is the code that I used when interacting with the custom widget (in my case, an image picker form field which can work with and display an `Uint8List` or an `XFile`):
```dart
onTap: () async {
  if (state.mounted) { // not sure if this is necessary
    final picker = ImagePicker();
    final image = await picker.pickImage(source: ImageSource.gallery);
    dynamic result; // this widget can keep track of both actual files on the filesystem, or a raw byte array
    if (typesEqual<T, XFile?>()) { // checks if the generic type of this widget T is an XFile? or a Uint8List?, then transform as necessary
      result = image;
    } else if (typesEqual<T, Uint8List?>()) {
      result = await image?.readAsBytes();
    }
    state.didChange(result as T); // not sure if casting as T is necessary
  }
},
```

This error messes up the focus of `FormBuilderTextField`s, requiring the user to tap twice before proper focus is gained and the keyboard is opened. The error persists until the app is restarted.

<details>
  <summary>Error report</summary>
<pre>
E/flutter (20202): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: A FocusNode was used after being disposed.
E/flutter (20202): Once you have called dispose() on a FocusNode, it can no longer be used.
E/flutter (20202): #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:114:9)
E/flutter (20202): #1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:120:6)
E/flutter (20202): #2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:288:12)
E/flutter (20202): #3      FocusNode._notify (package:flutter/src/widgets/focus_manager.dart:977:5)
E/flutter (20202): #4      FocusManager._applyFocusChange (package:flutter/src/widgets/focus_manager.dart:1715:12)
E/flutter (20202): #5      _rootRun (dart:async/zone.dart:1420:47)
E/flutter (20202): #6      _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (20202): #7      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter (20202): #8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter (20202): #9      _rootRun (dart:async/zone.dart:1428:13)
E/flutter (20202): #10     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (20202): #11     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter (20202): #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter (20202): #13     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)        
E/flutter (20202): #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
</pre>
</details>

**Comment by alcemirsantos** [comment]
@bdthombre's solution seems to work as a workaround for me.

**Comment by marcsinner** [comment]
> Still having this problem with custom `FormBuilderField` widgets. The error occurs every time that the current route/page is changed i.e. a new page is pushed onto the stack or a modal dialog is shown (thus unmounting the widget).
> 
> Important to note is if the custom widget is not interacted with, then the error does not occur, but this could be due to an error in my own code. Also adding your own `FocusNode` to the custom widget and then calling `FocusNode.dispose()` in the widget dispose callback does not fix the issue.
> 
> Apart from the widget layout code, here is the code that I used when interacting with the custom widget (in my case, an image picker form field which can work with and display an `Uint8List` or an `XFile`):
> 
> ```dart
> onTap: () async {
>   if (state.mounted) { // not sure if this is necessary
>     final picker = ImagePicker();
>     final image = await picker.pickImage(source: ImageSource.gallery);
>     dynamic result; // this widget can keep track of both actual files on the filesystem, or a raw byte array
>     if (typesEqual<T, XFile?>()) { // checks if the generic type of this widget T is an XFile? or a Uint8List?, then transform as necessary
>       result = image;
>     } else if (typesEqual<T, Uint8List?>()) {
>       result = await image?.readAsBytes();
>     }
>     state.didChange(result as T); // not sure if casting as T is necessary
>   }
> },
> ```
> 
> This error messes up the focus of `FormBuilderTextField`s, requiring the user to tap twice before proper focus is gained and the keyboard is opened. The error persists until the app is restarted.
> 
> Error report

Same here. Any updates how to solve this issue?

**Comment by marcsinner** [comment]
@mapokapo 
Same here. Any updates on how to solve this issue?
